// Web Push (RFC 8030/8291/8292) with nothing but WebCrypto — no npm deps, so
// the same file runs in the Supabase Deno runtime and under `node --test`
// (scripts/webpush.test.mjs proves the encryption against RFC 8291's own
// Appendix A vector — do not edit this file with that test red).
//
// aes128gcm content coding, single record, 2-byte-min padding delimiter 0x02;
// VAPID auth is an ES256 JWT over the push service origin.

const te = new TextEncoder();

export function b64uToBytes(s) {
  const pad = "=".repeat((4 - (s.length % 4)) % 4);
  const bin = atob(s.replace(/-/g, "+").replace(/_/g, "/") + pad);
  return Uint8Array.from(bin, (c) => c.charCodeAt(0));
}

export function bytesToB64u(bytes) {
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function concat(...parts) {
  const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0));
  let off = 0;
  for (const p of parts) {
    out.set(p, off);
    off += p.length;
  }
  return out;
}

// P-256 raw public key (0x04 | x | y, 65 bytes) → { x, y } JWK members.
function rawPubToJwkXY(raw) {
  if (raw.length !== 65 || raw[0] !== 0x04) throw new Error("webpush: bad P-256 public key");
  return { x: bytesToB64u(raw.slice(1, 33)), y: bytesToB64u(raw.slice(33, 65)) };
}

async function importEcdhPublic(raw) {
  return await crypto.subtle.importKey(
    "raw", raw, { name: "ECDH", namedCurve: "P-256" }, false, [],
  );
}

// d (b64u scalar) + matching raw public → ECDH private CryptoKey. Used for
// the RFC test vector; production uses a freshly generated ephemeral pair.
export async function importEcdhPrivate(dB64u, publicRaw) {
  const { x, y } = rawPubToJwkXY(publicRaw);
  return await crypto.subtle.importKey(
    "jwk",
    { kty: "EC", crv: "P-256", d: dB64u, x, y, ext: true },
    { name: "ECDH", namedCurve: "P-256" }, false, ["deriveBits"],
  );
}

async function hkdf(salt, ikm, info, bytes) {
  const key = await crypto.subtle.importKey("raw", ikm, "HKDF", false, ["deriveBits"]);
  const bits = await crypto.subtle.deriveBits(
    { name: "HKDF", hash: "SHA-256", salt, info }, key, bytes * 8,
  );
  return new Uint8Array(bits);
}

/**
 * Encrypt a payload for one subscription (RFC 8291, aes128gcm).
 * @param plaintext Uint8Array | string
 * @param keys { p256dh, auth } from PushSubscription.toJSON().keys
 * @param testing optional { asPrivate: CryptoKey, asPublicRaw: Uint8Array,
 *                salt: Uint8Array } — injected ONLY by the RFC vector test.
 * @returns Uint8Array — the complete request body (header ‖ ciphertext)
 */
export async function encrypt(plaintext, keys, testing) {
  const uaPublicRaw = b64uToBytes(keys.p256dh);
  const authSecret = b64uToBytes(keys.auth);
  const uaPublic = await importEcdhPublic(uaPublicRaw);

  let asPrivate, asPublicRaw, salt;
  if (testing) {
    ({ asPrivate, salt } = testing);
    asPublicRaw = testing.asPublicRaw;
  } else {
    const pair = await crypto.subtle.generateKey(
      { name: "ECDH", namedCurve: "P-256" }, true, ["deriveBits"],
    );
    asPrivate = pair.privateKey;
    asPublicRaw = new Uint8Array(await crypto.subtle.exportKey("raw", pair.publicKey));
    salt = crypto.getRandomValues(new Uint8Array(16));
  }

  const ecdhSecret = new Uint8Array(
    await crypto.subtle.deriveBits({ name: "ECDH", public: uaPublic }, asPrivate, 256),
  );

  // key_info = "WebPush: info" ‖ 0x00 ‖ ua_public ‖ as_public  (RFC 8291 §3.3)
  const keyInfo = concat(te.encode("WebPush: info\0"), uaPublicRaw, asPublicRaw);
  const ikm = await hkdf(authSecret, ecdhSecret, keyInfo, 32);
  const cek = await hkdf(salt, ikm, te.encode("Content-Encoding: aes128gcm\0"), 16);
  const nonce = await hkdf(salt, ikm, te.encode("Content-Encoding: nonce\0"), 12);

  // Single record: plaintext ‖ 0x02 (last-record padding delimiter, RFC 8188).
  const data = typeof plaintext === "string" ? te.encode(plaintext) : plaintext;
  const record = concat(data, new Uint8Array([0x02]));
  const gcmKey = await crypto.subtle.importKey("raw", cek, "AES-GCM", false, ["encrypt"]);
  const ciphertext = new Uint8Array(
    await crypto.subtle.encrypt({ name: "AES-GCM", iv: nonce }, gcmKey, record),
  );

  // aes128gcm header: salt(16) ‖ rs(4) ‖ idlen(1) ‖ keyid(= as_public, 65).
  const rs = new Uint8Array(4);
  new DataView(rs.buffer).setUint32(0, 4096);
  return concat(salt, rs, new Uint8Array([asPublicRaw.length]), asPublicRaw, ciphertext);
}

/**
 * VAPID Authorization header (RFC 8292 §3): ES256 JWT over the push-service
 * origin, signed with our long-lived VAPID key.
 * @param endpoint the subscription endpoint URL
 * @param vapid { subject: "mailto:…", publicKey: b64u raw, privateJwk: {x,y,d} }
 */
export async function vapidAuthHeader(endpoint, vapid) {
  const aud = new URL(endpoint).origin;
  const header = bytesToB64u(te.encode(JSON.stringify({ typ: "JWT", alg: "ES256" })));
  const payload = bytesToB64u(te.encode(JSON.stringify({
    aud,
    exp: Math.floor(Date.now() / 1000) + 12 * 3600,
    sub: vapid.subject,
  })));
  const signingInput = `${header}.${payload}`;
  const key = await crypto.subtle.importKey(
    "jwk",
    { kty: "EC", crv: "P-256", ...vapid.privateJwk, ext: true },
    { name: "ECDSA", namedCurve: "P-256" }, false, ["sign"],
  );
  // WebCrypto ECDSA emits raw r‖s (64 bytes) — exactly the JOSE form.
  const sig = new Uint8Array(await crypto.subtle.sign(
    { name: "ECDSA", hash: "SHA-256" }, key, te.encode(signingInput),
  ));
  return `vapid t=${signingInput}.${bytesToB64u(sig)}, k=${vapid.publicKey}`;
}

/**
 * Encrypt + POST one push message. Returns the push service's HTTP status
 * (201 = accepted; 404/410 = subscription dead, delete it). Never throws on
 * HTTP errors — network failures reject like any fetch.
 * @param sub { endpoint, keys: { p256dh, auth } }
 */
export async function sendWebPush(sub, payload, vapid, { ttl = 300, urgency = "high" } = {}) {
  const body = await encrypt(JSON.stringify(payload), sub.keys);
  const res = await fetch(sub.endpoint, {
    method: "POST",
    headers: {
      TTL: String(ttl),
      Urgency: urgency,
      "Content-Encoding": "aes128gcm",
      "Content-Type": "application/octet-stream",
      Authorization: await vapidAuthHeader(sub.endpoint, vapid),
    },
    body,
  });
  // Drain the body so the runtime doesn't hold the connection open.
  await res.arrayBuffer().catch(() => {});
  return res.status;
}
